// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhwrfhaicplqeoutwlws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhod3JmaGFpY3BscWVvdXR3bHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDYwOTksImV4cCI6MjA2NDk4MjA5OX0.BXlb7bekEUVxgqSb_SLdjcwKw41xnoXwoze6oSgvaqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);