// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzkrjfejvfhxzqjwgvoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6a3JqZmVqdmZoeHpxandndm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTM0OTMsImV4cCI6MjA2NDg2OTQ5M30.yoC4-awdGNDW4TJ8wGimnLSYpQMdcOKvtwg8sdrVuIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);